name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/nhstanko/discord-bot:latest
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN_TIME }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image to the registry github container registry
      run: docker push ghcr.io/nhstanko/discord-bot:latest
